// No lang variables

tinyMCE.addToLang('',{
bold_desc : 'Fet (Ctrl+B)',
italic_desc : 'Kursiv (Ctrl+I)',
underline_desc : 'Understreket (Ctrl+U)',
striketrough_desc : 'Strek-gjennom',
justifyleft_desc : 'Venstrejustert',
justifycenter_desc : 'Midtstilt',
justifyright_desc : 'Høyrejustert',
justifyfull_desc : 'Blokkjustering',
bullist_desc : 'Uordnet liste',
numlist_desc : 'Ordnet liste',
outdent_desc : 'Redusert inrykk',
indent_desc : 'Økt innrykk',
undo_desc : 'Angre (Ctrl+Z)',
redo_desc : 'Gjør om (Ctrl+Y)',
link_desc : 'Sett inn/rediger link',
unlink_desc : 'Fjern link',
image_desc : 'Sett inn/rediger bilde',
cleanup_desc : 'Rensk uryddig kode',
focus_alert : 'En editor-instans må velges før du bruker denne kommandoen.',
edit_confirm : 'Vil du bruke WYSIWYG modus for dette tekstområdet?',
insert_link_title : 'Sett inn/rediger link',
insert : 'Sett inn',
update : 'Oppdater',
cancel : 'Avbryt',
insert_link_url : 'Link URL',
insert_link_target : 'Mål',
insert_link_target_same : 'Åpne link i samme vindu',
insert_link_target_blank : 'Åpne link i nytt vindu',
insert_image_title : 'Sett inn/rediger bilde',
insert_image_src : 'Bilde URL',
insert_image_alt : 'Bilde beskrivelse',
help_desc : 'Hjelp',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'Kopier/Klipp/Lim inn er ikke tilgjengelig i Mozilla og Firefox.\nVil du ha mer informasjon om dette?',
popup_blocked : 'Beklager, men vi merker at sprettopp-stopperen din stopper vinduer som er nødvendig for funksjoner i dette programmet. Du må slå av sprettoppblokkering for denne siden for å utnytte programmet fult ut.'
});
