// UK lang variables

tinyMCE.addToLang('style',{
title : 'Rediger CSS Stil',
styleinfo_desc : 'Rediger CSS Stil',
text_tab : 'Tekst',
background_tab : 'Bakgrunn',
block_tab : 'Blokk',
box_tab : 'Boks',
border_tab : 'Kantlinje',
list_tab : 'Liste',
positioning_tab : 'Posisjon',
text_props : 'Tekst',
text_font : 'Skrift',
text_size : 'Størrelse',
text_weight : 'Vidde',
text_style : 'Stil',
text_variant : 'Variant',
text_lineheight : 'Linje høyde',
text_case : 'Case',
text_color : 'Farge',
text_decoration : 'Dekorasjon',
background_color : 'Bakgrunn farge',
background_image : 'Bakgrunnsbilde',
background_repeat : 'Repeter',
background_attachment : 'Vedlegg',
background_hpos : 'Horisontal posisjon',
background_vpos : 'Vertikal posisjon',
block_wordspacing : 'Ord spacing',
block_letterspacing : 'Bokstav spacing',
block_vertical_alignment : 'Vertikal oppstilling',
block_text_align : 'Tekst oppstilling',
block_text_indent : 'Tekst innrykk',
block_whitespace : 'Mellomrom',
block_display : 'Vis',
box_width : 'Vidde',
box_height : 'Høyde',
box_float : 'Float',
box_clear : 'Clear',
padding : 'Padding',
same : 'Samme for alle',
top : 'Topp',
right : 'Høyre',
bottom : 'Bunn,
left : 'Venstre',
margin : 'Margin',
style : 'Stil',
width : 'Vidde',
height : 'Høyde',
color : 'Farge',
list_type : 'Type',
bullet_image : 'Bullet image',
position : 'Posisjon',
positioning_type : 'Type',
visibility : 'Synlighet',
zindex : 'Z-index',
overflow : 'Overflow',
placement : 'Plassering',
clip : 'Clip'
});
