// UK lang variables

tinyMCE.addToLang('table',{
general_tab : 'Generell',
advanced_tab : 'Avansert',
general_props : 'Generelle innstillinger',
advanced_props : 'Avanserte innstillinger',
desc : 'Sett inn ny tabell',
row_before_desc : 'Sett inn rad før',
row_after_desc : 'Sett inn rad etter',
delete_row_desc : 'Slett rad',
col_before_desc : 'Sett inn kolonne før',
col_after_desc : 'Sett inn kolonne etter',
delete_col_desc : 'Fjern kolonne',
rowtype : 'Row in table part',
title : 'Sett inn/rediger tabell',
width : 'Vidde',
height : 'Høyde',
cols : 'Kolonner',
rows : 'Rader',
cellspacing : 'Cellspacing',
cellpadding : 'Cellpadding',
border : 'Kantlinje',
align : 'Plassering',
align_default : 'Standard',
align_left : 'Venstre',
align_right : 'Høyre',
align_middle : 'Sentrer',
row_title : 'Tabell rad innstillinger',
cell_title : 'Tabell celle innstillinger',
cell_type : 'Celle type',
row_desc : 'Tabell rad innstillinger',
cell_desc : 'Tabell celle innstillinger',
valign : 'Vertikal plassering',
align_top : 'Topp',
align_bottom : 'Bunn',
props_desc : 'Tabell innstillinger',
bordercolor : 'Kantlinje farge',
bgcolor : 'Bakgrunnsfarge',
merge_cells_title : 'Slå sammen celler',
split_cells_desc : 'Del opp celler',
merge_cells_desc : 'Slå sammen celler',
cut_row_desc : 'Fjern',
copy_row_desc : 'Kopier rad',
paste_row_before_desc : 'Lim inn rad før',
paste_row_after_desc : 'Lim inn rad etter',
id : 'Id',
style: 'Stil',
langdir : 'Språk retning',
langcode : 'Språkkode',
mime : 'Mål MIME type',
ltr : 'Venstre mot høyre',
rtl : 'Høyre mot venstre',
bgimage : 'Bakgrunnsbilde',
summary : 'Sammendrag',
td : "Data",
th : "Header",
cell_cell : 'Oppdater denne cellen',
cell_row : 'Oppdater alle cellen i raden',
cell_all : 'Oppdater alle cellen i tabellen',
row_row : 'Oppdater denne raden',
row_odd : 'Oppdater ulike rader i tabell',
row_even : 'Oppdater like rader i tabell',
row_all : 'Oppdater alle radene i tabell',
thead : 'Tabell Head',
tbody : 'Tabell Body',
tfoot : 'Tabbel Foot',
del : 'Slett tabell',
scope : 'Scope',
row : 'Row',
col : 'Col',
rowgroup : 'Row Group',
colgroup : 'Col Group',
col_limit : 'You\'ve exceeded the maximum number of columns of {$cols}.',
row_limit : 'You\'ve exceeded the maximum number of rows of {$rows}.',
cell_limit : 'You\'ve exceeded the maximum number of cells of {$cells}.',
missing_scope: 'Are you sure you want to continue without specifying a scope for this table header cell. Without it, it may be difficult for some users with disabilities to understand the content or data displayed of the table.'
});
