// No lang variables

tinyMCE.addToLang('advlink',{
general_tab : 'Generell',
popup_tab : 'Popup',
events_tab : 'Hendelser',
advanced_tab : 'Avansert',
general_props : 'Generelle innstillinger',
popup_props : 'Popup innstillinger',
event_props : 'Hendelser',
advanced_props : 'Avanserte innstillinger',
popup_opts : 'Valg',
anchor_names : 'Anker',
target_same : 'Åpne i dette vinduet / rammen',
target_parent : 'Åpne i gjeldende vindu / ramme',
target_top : 'Åpne i topprammen (erstatter alle rammer)',
target_blank : 'Åpne i nytt vindu',
popup : 'Javascript popup',
popup_url : 'Popup URL',
popup_name : 'Vindu navn',
popup_return : 'Sett inn \'return false\'',
popup_scrollbars : 'Vis scrollbars',
popup_statusbar : 'Vis status bar',
popup_toolbar : 'Vis verktøyknapper',
popup_menubar : 'Vis meny',
popup_location : 'Vis location bar',
popup_resizable : 'Endre størrelse på vindu',
popup_dependent : 'Avhengighet (bare Mozilla/Firefox)',
popup_size : 'Størrelse',
popup_position : 'Posisjon (X/Y)',
id : 'Id',
style: 'Stil',
classes : 'Classes',
target_name : 'Mål navn',
langdir : 'Språk retning',
target_langcode : 'Mål språk',
langcode : 'Språk kode',
encoding : 'Mål tegnkoding',
mime : 'Mål MIME type',
rel : 'Sammenheng side til mål',
rev : 'Sammenheng mål til side',
tabindex : 'Tabindex',
accesskey : 'Accesskey',
ltr : 'Venstre mot høyre',
rtl : 'Høyre mot venstre'
});
