// UK lang variables

tinyMCE.addToLang('',{
theme_style_select : '-- Stiler --',
theme_code_desc : 'Rediger HTML-kilde',
theme_code_title : 'HTML-kilde Editor',
theme_code_wordwrap : 'Tekstbryting',
theme_sub_desc : 'Subscript',
theme_sup_desc : 'Superscript',
theme_hr_desc : 'Sett inn horisontal linje',
theme_removeformat_desc : 'Fjern formatering',
theme_custom1_desc : 'Din egen beskrivelse her',
insert_image_border : 'Kantlinje',
insert_image_dimensions : 'Dimensjoner',
insert_image_vspace : 'Vertikal space',
insert_image_hspace : 'Horisontal space',
insert_image_align : 'Alignment',
insert_image_align_default : '-- Ikke satt --',
insert_image_align_baseline : 'Baseline',
insert_image_align_top : 'Top',
insert_image_align_middle : 'Middle',
insert_image_align_bottom : 'Bottom',
insert_image_align_texttop : 'TextTop',
insert_image_align_absmiddle : 'Absolute Middle',
insert_image_align_absbottom : 'Absolute Bottom',
insert_image_align_left : 'Left',
insert_image_align_right : 'Right',
theme_font_size : '-- Skriftstørrelse --',
theme_fontdefault : '-- Skrifttype --',
theme_block : '-- Format --',
theme_paragraph : 'Paragraph',
theme_div : 'Div',
theme_address : 'Address',
theme_pre : 'Preformatted',
theme_h1 : 'Heading 1',
theme_h2 : 'Heading 2',
theme_h3 : 'Heading 3',
theme_h4 : 'Heading 4',
theme_h5 : 'Heading 5',
theme_h6 : 'Heading 6',
theme_blockquote : 'Blockquote',
theme_code : 'Code',
theme_samp : 'Code sample',
theme_dt : 'Definition term ',
theme_dd : 'Definition description',
theme_colorpicker_title : 'Velg farge',
theme_colorpicker_apply : 'Sett inn',
theme_forecolor_desc : 'Velg tekstfarge',
theme_backcolor_desc : 'Velg bagrunnsfarge',
theme_charmap_title : 'Velg spesialtegn',
theme_charmap_desc : 'Sett inn spesialtegn',
theme_visualaid_desc : 'Slå av/på usynlige elementer',
insert_anchor_title : 'Sett inn/rediger anker',
insert_anchor_name : 'Anker navn',
theme_anchor_desc : 'Sett inn/rediger anker',
theme_insert_link_titlefield : 'Tittel',
theme_clipboard_msg : 'Kopier/Klipp/Lim inn er ikke tilgjenglig i Mozilla og Firefox.\nVil du ha mer informasjon om dette?',
theme_path : 'Path',
cut_desc : 'Klipp',
copy_desc : 'Kopier',
paste_desc : 'Lim inn',
link_list : 'Link liste',
image_list : 'Bilde liste',
browse : 'Browse',
image_props_desc : 'Bilde properties',
newdocument_desc : 'Nytt dokument',
class_name : 'Class',
newdocument : 'Are you sure you want clear all contents?',
about_title : 'About TinyMCE',
about : 'About',
license : 'License',
plugins : 'Plugins',
plugin : 'Plugin',
author : 'Author',
version : 'Version',
loaded_plugins : 'Loaded plugins',
help : 'Hjelp',
not_set : '-- Ikke satt --',
close : 'Close',
toolbar_focus : 'Gå til verktøyknapper - Alt+Q, Gå til editor - Alt-Z, Gå til elementsti - Alt-X'
});
